name: easy
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter
  mask_text_input_formatter: ^1.2.1
  shared_preferences:
  sqflite: ^1.0.0
  path_provider:
  adobe_xd: ^1.1.0+1
  local_auth:
  google_sign_in:
  popup_menu: ^1.0.5
  device_info:
  location: ^3.0.0
  fluttertoast: ^8.0.3
  awesome_dialog: ^1.3.2
  audioplayers: ^0.13.2
  android_alarm_manager: ^2.0.0
  battery: ^2.0.1
  provider: ^3.0.0+1
  flutter_xmllayout_helpers: ^0.0.9
  http: ^0.12.1
  flutter_session:
  get: ^4.1.1
  telephony: ^0.1.2
  flutter_speed_dial: ^3.0.5
  custom_switch: ^0.0.1
  url_launcher: ^6.0.3
  background_fetch: ^0.7.2
  workmanager: ^0.2.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  volume_watcher: ^1.3.1
  flutter_svg:
dev_dependencies:

  flutter_launcher_icons: "^0.8.0"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/alarm.mp3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
